pivotview/ej2-javascript-pivotview-toc.html
pivotview/ej2-typescript-pivotview-toc.html

documentation(EJ2-71942): changed toc

---

pivotview/ej2-javascript-pivotview-toc.html
pivotview/ej2-typescript-pivotview-toc.html

documentation(EJ2-71942): toc issue resolved

---

pivotview/ej2-typescript-pivotview-toc.html

documentation(EJ2-71942): changed toc structure

---

pivotview/ts/paging.md

documentation(EJ2-71942): Fixed Front Matter issues

---

ej2-javascript/pivotview/globalization-and-localization.md
ej2-javascript/pivotview/tool-bar.md

Documentation(833199): Fixed Broken link issue

---

ej2-javascript/pivotview/js/connecting-to-data-source/microsoft-sql-server.md
ej2-javascript/pivotview/js/connecting-to-data-source/mongodb.md
ej2-javascript/pivotview/js/connecting-to-data-source/mysql.md
ej2-javascript/pivotview/js/connecting-to-data-source/postgresql.md
ej2-javascript/pivotview/ts/connecting-to-data-source/microsoft-sql-server.md
ej2-javascript/pivotview/ts/connecting-to-data-source/mongodb.md
ej2-javascript/pivotview/ts/connecting-to-data-source/mysql.md
ej2-javascript/pivotview/ts/connecting-to-data-source/postgresql.md

 Documentation(EJ2-834206) : To include UG for additional datasource for EJ2 Pivot Table

---

ej2-javascript/code-snippet/pivot-table/pivot-table-cs186/index.js
ej2-javascript/code-snippet/pivot-table/pivot-table-cs186/index.ts
ej2-javascript/code-snippet/pivot-table/pivot-table-cs240/index.js
ej2-javascript/code-snippet/pivot-table/pivot-table-cs240/index.ts
ej2-javascript/code-snippet/pivot-table/pivot-table-cs247/index.js
ej2-javascript/code-snippet/pivot-table/pivot-table-cs247/index.ts
ej2-javascript/code-snippet/pivot-table/pivot-table-cs325/index.ts
ej2-javascript/code-snippet/pivot-table/pivot-table-cs452/index.ts

samples not working on typescript and javascript UG

bug(EJ2-830002) : samples not working on UG

---

ej2-javascript/code-snippet/pivot-table/pivot-table-cs497/index.js
ej2-javascript/pivotview/ej2-typescript-pivotview-toc.html
ej2-javascript/pivotview/js/print.md
ej2-javascript/pivotview/ts/print.md

Updated Section-1: UG document for frequently asked requirements in Pivot Table.

documentation(824951): Section-1: UG document for frequently asked requirements in Pivot Table.

---

ej2-javascript/code-snippet/pivot-table/pivot-table-cs243/index.js

cell template sample not working properly in javascript

Bug(EJ2-839345) : cell template sample not working properly in javascript

---

ej2-javascript/pivotview/how-to/display-value-in-hrs-min-sec-format.md
ej2-javascript/pivotview/js/pdf-export.md
ej2-javascript/pivotview/ts/pdf-export.md

Remove the API background shading

Documentation(EJ2-847974) : Remove the API background shading

---

ej2-javascript/pivotview/ej2-javascript-pivotview-toc.html
ej2-javascript/pivotview/ej2-typescript-pivotview-toc.html

To update toc file in Typescript and javascript platform

Documentation(EJ2-849790): To update toc file in Typescript and javascript platform

---

ej2-javascript/code-snippet/pivot-grid/icon-customize-cs1/systemjs.config.js
ej2-javascript/code-snippet/pivot-grid/pivot-grid-cs1/index.js
ej2-javascript/code-snippet/pivot-grid/pivot-grid-cs1/systemjs.config.js
ej2-javascript/code-snippet/pivot-grid/pivot-grid-cs2/index.js
ej2-javascript/code-snippet/pivot-grid/pivot-grid-cs2/systemjs.config.js
ej2-javascript/code-snippet/pivot-table/chart-export-cs1/index.ts
ej2-javascript/code-snippet/pivot-table/chart-export-cs3/index.ts
ej2-javascript/code-snippet/pivot-table/chart-export-cs4/index.ts
ej2-javascript/code-snippet/pivot-table/chart-print-cs2/index.ts
ej2-javascript/code-snippet/pivot-table/chart-print-cs3/index.ts
ej2-javascript/code-snippet/pivot-table/pivot-table-cs22/index.ts
ej2-javascript/code-snippet/pivot-table/pivot-table-cs241/index.js
ej2-javascript/code-snippet/pivot-table/pivot-table-cs241/index.ts
ej2-javascript/code-snippet/pivot-table/pivot-table-cs297/index.js
ej2-javascript/code-snippet/pivot-table/pivot-table-cs297/index.ts
ej2-javascript/code-snippet/pivot-table/pivot-table-cs460/index.js
ej2-javascript/code-snippet/pivot-table/pivot-table-cs460/index.ts
ej2-javascript/code-snippet/pivot-table/pivot-table-cs501/systemjs.config.js
ej2-javascript/code-snippet/pivot-table/pivot-table-cs92/index.js
ej2-javascript/code-snippet/pivot-table/pivot-table-cs92/index.ts

To resolve the preview sample issues typescript

Bug(EJ2-856552): To resolve the preview sample issues typescript

---

ej2-javascript/pivotview/js/server-side-pivot-engine.md
ej2-javascript/pivotview/ts/server-side-pivot-engine.md

To resolve the issues in server-side-pivot-engine topic

Documentation(EJ2-856358) : To resolve the issues in server-side-pivot-engine topic

---

ej2-javascript/code-snippet/pivot-table/pivot-table-cs500/index.js
ej2-javascript/code-snippet/pivot-table/pivot-table-cs500/index.ts

Load the desired report sample issue fixed.

bug(EJ2-861152): Load the desired report sample issue fixed.

---

ej2-javascript/pivotview/js/accessibility.md
ej2-javascript/pivotview/ts/accessibility.md

Task: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/854623

854623: To improve TS&JS accessibility UG document

---

ej2-javascript/pivotview/js/pivot-chart.md
ej2-javascript/pivotview/ts/pivot-chart.md

Include the UG documentation for displaying chart series points in the desired color palettes.

Documentation(EJ2-856590) : To include the UG Documentation for for display chart series points in desired color palettes

---

ej2-javascript/pivotview/js/accessibility.md
ej2-javascript/pivotview/ts/accessibility.md

Need to modified the icons on accessibility document. The Icons are newly created for the compilance measuring.
[866555](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/866555)
NA
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
Provide the details about the areas or combinations which have been tested against this code changes.
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
NA
UX changes got approval if UI is …

866555: Need to modified the icons on accessibility document

---

ej2-javascript/pivotview/globalization-and-localization.md

To update locale keywords and corresponding text

Documentation(EJ2-866811) - To update locale keywords and corresponding text

---

ej2-javascript/code-snippet/pivot-table/pivot-table-cs501/index.ts

To resolve preview sample issues

Documentation(EJ2-866811) - To resolve preview sample issues

---

ej2-javascript/code-snippet/pivot-table/single-page-mode/datasource.ts
ej2-javascript/code-snippet/pivot-table/single-page-mode/es5-datasource.js
ej2-javascript/code-snippet/pivot-table/single-page-mode/index.css
ej2-javascript/code-snippet/pivot-table/single-page-mode/index.js
ej2-javascript/code-snippet/pivot-table/single-page-mode/index.ts
ej2-javascript/code-snippet/pivot-table/single-page-mode/js/index.html
ej2-javascript/code-snippet/pivot-table/single-page-mode/systemjs.config.js
ej2-javascript/code-snippet/pivot-table/single-page-mode/ts/index.html
ej2-javascript/pivotview/ej2-javascript-pivotview-toc.html
ej2-javascript/pivotview/ej2-typescript-pivotview-toc.html
ej2-javascript/pivotview/js/data-compression.md
ej2-javascript/pivotview/js/excel-export.md
ej2-javascript/pivotview/js/olap.md
ej2-javascript/pivotview/js/pdf-export.md
ej2-javascript/pivotview/js/sorting.md
ej2-javascript/pivotview/js/virtual-scrolling.md
ej2-javascript/pivotview/ts/data-compression.md
ej2-javascript/pivotview/ts/excel-export.md
ej2-javascript/pivotview/ts/olap.md
ej2-javascript/pivotview/ts/sorting.md
ej2-javascript/pivotview/ts/virtual-scrolling.md

UG document for single page mode, value sorting and OLAP virtualization.

875839: UG document for single page mode, value sorting, OLAP virtualization and Data Compression

---

ej2-javascript/pivotview/js/virtual-scrolling.md
ej2-javascript/pivotview/ts/virtual-scrolling.md

Updating the virtual-scrolling file in UG

875577: Updating the virtual-scrolling file in UG
